apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: memcached-reservation
  name: memcached-reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: memcached-reservation
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: memcached-reservation
    spec:
      nodeName: cpu-08
      containers:
        - env:
            - name: MEMCACHED_CACHE_SIZE
              # value: "128"
              value: "512"
            - name: MEMCACHED_THREADS
              # value: "2"
              value: "8"
            - name: MEMCACHED_MAX_CONNECTIONS
              value: "8192"
          image: memcached
          imagePullPolicy: IfNotPresent
          name: hotel-reserv-reservation-mmc
          ports:
            - containerPort: 11211
          #resources:
          #  requests:
          #    cpu: "860m"
          #  limits:
          #    cpu: "860m"
      restartPolicy: Always
status: {}
